openapi: 3.0.0
info:
  title: Starbic Authentication System
  version: 1.0.0
paths:
  /health:
    get:
      summary: Service health check
      responses:
        '200':
          description: Service status information